Dp interface transfer
karibou-ch/karibou-wallet pull request #18
Opened 2017-07-09 16:54 UTC by patedavid

2017-07-10 12:46 UTC, evaletolab requested changes
super, regarde les comments pour finaliser. thks

2017-07-10 12:46 UTC, evaletolab commented on lib/transfer.ts
> +    .then((transferList) => {
super mais pourquoi tu n'utilises pas transfert list pour valider dest[].transferId ??? c'est ce que j'imagine, il faut valider la vesrion local en mémoire est correcte! après voir reçu trlist : 
- check transfer id et tous les autres fields qui peuvent être checké!!

2017-07-10 12:46 UTC, evaletolab commented on lib/transfer.ts
> +              this.dest[i].logs.push("Executed");
ton log doit être plus utile que ça amount, date, dest enfin une sorte de dest.toString()

2017-07-10 12:46 UTC, evaletolab commented on lib/transfer.ts
> +    for (let i in this.dest) {
please utilise les fonction de l'object array Array.find(...)

2017-07-10 12:46 UTC, evaletolab commented on lib/transfer.ts
> +      return Promise.reject(new Error("Account for the transfer not found."));
svp, ajoute {} même si ya une instruction, c'est le bug typique lorsque tu ajoutes une deuxième inst

2017-07-10 12:46 UTC, evaletolab commented on lib/transfer.ts
> +  getState(account:Account) {
a quoi sert getState()?

2017-07-24 16:55 UTC, patedavid commented on lib/transfer.ts
> +  getState(account:Account) {
Il permet de suivre l'état d'un transfert pour un account donné (si il a été effectué, si un refund a déjà été fait)

2017-07-24 17:09 UTC, patedavid commented on lib/transfer.ts
> +    for (let i in this.dest) {
corrigé

2017-07-24 17:09 UTC, patedavid commented on lib/transfer.ts
> +      return Promise.reject(new Error("Account for the transfer not found."));
corrigé

2017-07-24 17:09 UTC, patedavid commented on lib/transfer.ts
> +              this.dest[i].logs.push("Executed");
Je l'ai un peu modifié:

2020-06-09 20:12 UTC, merged